// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreatePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4);
}

export function CreateTeam(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTeam'](arg1, arg2, arg3);
}

export function CreateTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function DetectCLIs() {
  return window['go']['main']['App']['DetectCLIs']();
}

export function GetAgents(arg1) {
  return window['go']['main']['App']['GetAgents'](arg1);
}

export function GetGlobalPrompt() {
  return window['go']['main']['App']['GetGlobalPrompt']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetTeam(arg1) {
  return window['go']['main']['App']['GetTeam'](arg1);
}

export function GetTerminalSessions(arg1) {
  return window['go']['main']['App']['GetTerminalSessions'](arg1);
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListTeams() {
  return window['go']['main']['App']['ListTeams']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartTerminal(arg1) {
  return window['go']['main']['App']['RestartTerminal'](arg1);
}

export function SendPromptToAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPromptToAgent'](arg1, arg2, arg3);
}

export function SetGlobalPrompt(arg1) {
  return window['go']['main']['App']['SetGlobalPrompt'](arg1);
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTeam(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTeam'](arg1, arg2, arg3, arg4);
}

export function WatchChatDir(arg1) {
  return window['go']['main']['App']['WatchChatDir'](arg1);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
