// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastToTeam(arg1, arg2, arg3) {
  return window['go']['main']['App']['BroadcastToTeam'](arg1, arg2, arg3);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreatePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4);
}

export function CreateTeam(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTeam'](arg1, arg2, arg3);
}

export function CreateTerminal(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteRoom(arg1) {
  return window['go']['main']['App']['DeleteRoom'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function DetectCLIs() {
  return window['go']['main']['App']['DetectCLIs']();
}

export function GetAgents(arg1) {
  return window['go']['main']['App']['GetAgents'](arg1);
}

export function GetGlobalPrompt() {
  return window['go']['main']['App']['GetGlobalPrompt']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetRoomSummary(arg1) {
  return window['go']['main']['App']['GetRoomSummary'](arg1);
}

export function GetRoomTranscript(arg1) {
  return window['go']['main']['App']['GetRoomTranscript'](arg1);
}

export function GetTeam(arg1) {
  return window['go']['main']['App']['GetTeam'](arg1);
}

export function GetTerminalSessions(arg1) {
  return window['go']['main']['App']['GetTerminalSessions'](arg1);
}

export function GetVoiceStatus() {
  return window['go']['main']['App']['GetVoiceStatus']();
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListRooms() {
  return window['go']['main']['App']['ListRooms']();
}

export function ListTeams() {
  return window['go']['main']['App']['ListTeams']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenTeamFromConfig(arg1) {
  return window['go']['main']['App']['OpenTeamFromConfig'](arg1);
}

export function RenderSummaryPrompt(arg1) {
  return window['go']['main']['App']['RenderSummaryPrompt'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartTerminal(arg1) {
  return window['go']['main']['App']['RestartTerminal'](arg1);
}

export function ResumeTerminal(arg1) {
  return window['go']['main']['App']['ResumeTerminal'](arg1);
}

export function SaveRoomSummary(arg1, arg2) {
  return window['go']['main']['App']['SaveRoomSummary'](arg1, arg2);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SendPromptToAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPromptToAgent'](arg1, arg2, arg3);
}

export function SetCustomPrompt(arg1, arg2) {
  return window['go']['main']['App']['SetCustomPrompt'](arg1, arg2);
}

export function SetGlobalPrompt(arg1) {
  return window['go']['main']['App']['SetGlobalPrompt'](arg1);
}

export function SetTeamManager(arg1, arg2) {
  return window['go']['main']['App']['SetTeamManager'](arg1, arg2);
}

export function SetTeamObserver(arg1, arg2) {
  return window['go']['main']['App']['SetTeamObserver'](arg1, arg2);
}

export function SetVoiceConfig(arg1) {
  return window['go']['main']['App']['SetVoiceConfig'](arg1);
}

export function StartVoiceCapture(arg1) {
  return window['go']['main']['App']['StartVoiceCapture'](arg1);
}

export function StopVoiceCapture(arg1) {
  return window['go']['main']['App']['StopVoiceCapture'](arg1);
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTeam(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTeam'](arg1, arg2, arg3, arg4);
}

export function WatchChatDir(arg1) {
  return window['go']['main']['App']['WatchChatDir'](arg1);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
