// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {prompt} from '../models';
import {team} from '../models';
import {cli} from '../models';
import {watcher} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<prompt.Prompt>;

export function CreateTeam(arg1:string,arg2:string,arg3:Array<team.AgentConfig>):Promise<team.Team>;

export function CreateTerminal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DeletePrompt(arg1:string):Promise<void>;

export function DeleteTeam(arg1:string):Promise<void>;

export function DetectCLIs():Promise<Array<cli.CLIInfo>>;

export function GetAgents(arg1:string):Promise<Record<string, watcher.Agent>>;

export function GetGlobalPrompt():Promise<string>;

export function GetMessages(arg1:string):Promise<Array<watcher.Message>>;

export function GetPrompt(arg1:string):Promise<prompt.Prompt>;

export function GetTeam(arg1:string):Promise<team.Team>;

export function GetTerminalSessions(arg1:string):Promise<Array<Record<string, string>>>;

export function ListPrompts():Promise<Array<prompt.Prompt>>;

export function ListTeams():Promise<Array<team.Team>>;

export function OpenDirectoryDialog():Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartTerminal(arg1:string):Promise<string>;

export function SendPromptToAgent(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function SetGlobalPrompt(arg1:string):Promise<void>;

export function UpdatePrompt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<prompt.Prompt>;

export function UpdateTeam(arg1:string,arg2:string,arg3:string,arg4:Array<team.AgentConfig>):Promise<team.Team>;

export function WatchChatDir(arg1:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
